Repository 34th-SOPKATHON-ANDROID-TEAM3/Android, pull requests merged in 2024-05, with the labels that each got.

#9 [feat] #8 shake sensor
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/sopkathon/android3/presentation/MainActivity.kt
  app/src/main/java/org/sopt/sopkathon/android3/presentation/SensorUtil.kt
Labels: 기초 세팅

#13 [feat] #12 dto, api
  app/src/main/java/org/sopt/sopkathon/android3/data/ApiFactory.kt
  app/src/main/java/org/sopt/sopkathon/android3/data/model/request/RequestPatchAnswerDto.kt
  app/src/main/java/org/sopt/sopkathon/android3/data/model/response/ResponseGetCollectedStonesDto.kt
  app/src/main/java/org/sopt/sopkathon/android3/data/model/response/ResponseGetStoneDetailDto.kt
  app/src/main/java/org/sopt/sopkathon/android3/data/model/response/ResponseGetTodayStoneDto.kt
  app/src/main/java/org/sopt/sopkathon/android3/data/service/StoneApi.kt
Labels: 서버 연결

#23 [feat] #17 상세 페이지 UI 구현 및 서버 통신
  app/src/main/java/org/sopt/sopkathon/android3/presentation/detail/DetailActivity.kt
  app/src/main/java/org/sopt/sopkathon/android3/presentation/detail/DetailViewModel.kt
  app/src/main/res/drawable/shape_white_line_black_fill_left10_bottom10_rect.xml
  app/src/main/res/layout/activity_detail.xml
Labels: 나경 👽, UI, 서버 연결

#24 [feat] #16 질문 페이지 UI 구현 및 서버 통신
  app/src/main/java/org/sopt/sopkathon/android3/presentation/question/QuestionActivity.kt
  app/src/main/java/org/sopt/sopkathon/android3/presentation/question/QuestionState.kt
  app/src/main/java/org/sopt/sopkathon/android3/presentation/question/QuestionViewModel.kt
  app/src/main/res/drawable/ic_answer_box.xml
  app/src/main/res/drawable/ic_btn_save.xml
  app/src/main/res/drawable/ic_date_bar.xml
  app/src/main/res/drawable/ic_done.xml
  app/src/main/res/layout/activity_question.xml
Labels: UI, 서버 연결, 윤서 🌻

#25 [feat] #15 캘린더 페이지 UI 구현 및 서버 통신
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/sopkathon/android3/SplashActivity.kt
  app/src/main/java/org/sopt/sopkathon/android3/presentation/calendar/CalendarActivity.kt
  app/src/main/java/org/sopt/sopkathon/android3/presentation/calendar/CalendarViewModel.kt
  app/src/main/java/org/sopt/sopkathon/android3/presentation/calendar/CalendarWarningDialogFragment.kt
  app/src/main/java/org/sopt/sopkathon/android3/presentation/calendar/adapter/CalendarAdapter.kt
  app/src/main/java/org/sopt/sopkathon/android3/presentation/calendar/viewholder/CalendarViewHolder.kt
  app/src/main/res/drawable/ic_calendar_close.xml
  app/src/main/res/drawable/img_calendar_dialog_warning.xml
  app/src/main/res/drawable/shape_white_fill_20_rect.xml
  app/src/main/res/layout/activity_calendar.xml
  app/src/main/res/layout/fragment_calendar_warning_dialog.xml
  app/src/main/res/layout/item_rock.xml
  gradle/libs.versions.toml
Labels: UI, 기능 구현, 서버 연결, 가을 🐰

#27 [refactor] #26 typography 디자인 시스템 변경 사항 적용
  app/src/main/res/values/typography.xml
Labels: 나경 👽, 기초 세팅

#31 [feat] 질문 페이지 UI 디테일 구현
  app/src/main/res/drawable/ic_answer_box.xml
  app/src/main/res/drawable/ic_btn_save.xml
  app/src/main/res/drawable/ic_date_bar.xml
  app/src/main/res/drawable/ic_logo_white.xml
  app/src/main/res/drawable/shape_gray_fill_circle.xml
  app/src/main/res/layout/activity_question.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/themes.xml
Labels: UI, 윤서 🌻

#32 [feat] #28 상세 페이지 UI 디테일 구현
  app/src/main/res/layout/activity_detail.xml
Labels: 나경 👽, UI
